# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oH2X-FDVnfstP-aHGIzvRWV7Ovdk6yhP
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

class TitanicEDA:
    def __init__(self, dataset_path):
        self.dataset_path = dataset_path
        self.data = None
    def load_data(self):
        self.data = pd.read_csv(self.dataset_path)
        return self.data.head()

    def summary_statistics(self):
        return self.data.describe(include='all')

    def visualize_survival_distribution(self, feature):
        plt.figure(figsize=(10, 6))
        sns.countplot(x=feature, hue='Survived', data=self.data, palette='viridis')
        plt.title(f'Survival Distribution based on {feature}')
        plt.savefig(f'{feature}_survival_distribution.png')
        plt.show()

dataset_path = r"/content/train.csv"
titanic_eda = TitanicEDA(dataset_path)
titanic_eda.load_data()

summary_stats = titanic_eda.summary_statistics()
summary_stats

titanic_eda.visualize_survival_distribution('Pclass')

titanic_eda.visualize_survival_distribution('Sex')

titanic_eda.data['AgeBin'] = pd.cut(titanic_eda.data['Age'], bins=[0, 12, 18, 25, 35, 60, 80], labels=['0-12', '13-18', '19-25', '26-35', '36-60', '61-80'])
titanic_eda.visualize_survival_distribution('AgeBin')